from .letters_validator import validate_letters
from .phone_validator import validate_phone_number
from .permit_validator import validate_permit_number
from .email_validator import validate_email
from .postal_code_validator import validate_postal_code