"""Link MedicalRecord to Appointment and Animal

Revision ID: 4f6425d2748c
Revises: 8ed1a7789ce6
Create Date: 2025-04-18 19:36:11.882224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6425d2748c'
down_revision: Union[str, None] = '8ed1a7789ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medical_records_id', table_name='medical_records')
    op.drop_table('medical_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('animal_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('diagnosis', sa.TEXT(), nullable=True),
    sa.Column('treatment', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_records_id', 'medical_records', ['id'], unique=False)
    # ### end Alembic commands ###
