"""Add login security fields

Revision ID: 8f020866ea61
Revises: 50409e86bbbb
Create Date: 2025-05-13 10:45:55.533699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f020866ea61'
down_revision: Union[str, None] = '50409e86bbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- dla SQLite: batch_alter_table z server_default ---
    with op.batch_alter_table('clients') as batch_op:
        batch_op.add_column(sa.Column(
            'failed_login_attempts',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        ))
        batch_op.add_column(sa.Column(
            'locked_until',
            sa.DateTime(),
            nullable=True
        ))

    with op.batch_alter_table('consultants') as batch_op:
        batch_op.add_column(sa.Column(
            'failed_login_attempts',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        ))
        batch_op.add_column(sa.Column(
            'locked_until',
            sa.DateTime(),
            nullable=True
        ))

    with op.batch_alter_table('doctors') as batch_op:
        batch_op.add_column(sa.Column(
            'failed_login_attempts',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0')
        ))
        batch_op.add_column(sa.Column(
            'locked_until',
            sa.DateTime(),
            nullable=True
        ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'locked_until')
    op.drop_column('doctors', 'failed_login_attempts')
    op.drop_column('consultants', 'locked_until')
    op.drop_column('consultants', 'failed_login_attempts')
    op.drop_column('clients', 'locked_until')
    op.drop_column('clients', 'failed_login_attempts')
    # ### end Alembic commands ###
