"""invoice

Revision ID: cdda26e8da7e
Revises: 278e63d32849
Create Date: 2025-06-11 05:18:00.934434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdda26e8da7e'
down_revision: Union[str, None] = '278e63d32849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: create invoices table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invoices',
        sa.Column('id', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Numeric(10, 2), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default=sa.text("'pending'")),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
    )
    op.create_index('ix_invoices_id', 'invoices', ['id'], unique=False)
    op.create_index('ix_invoices_client_id', 'invoices', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: drop invoices table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_client_id', table_name='invoices')
    op.drop_index('ix_invoices_id', table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
