"""Add visit table

Revision ID: e6470fae8e67
Revises: 663473613c8b
Create Date: 2025-04-11 20:59:54.372055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6470fae8e67'
down_revision: Union[str, None] = '663473613c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_datetime', sa.DateTime(), nullable=False, comment='Data i czas wizyty'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Powód wizyty lub rodzaj usługi'),
    sa.Column('status', sa.String(), nullable=False, comment='Status wizyty: zaplanowana, odwołana, zakończona'),
    sa.Column('doctor_id', sa.Integer(), nullable=False, comment='ID lekarza obsługującego wizytę'),
    sa.Column('animal_id', sa.Integer(), nullable=False, comment='ID zwierzęcia będącego pacjentem'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='ID właściciela zwierzęcia'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Dodatkowe informacje i uwagi dotyczące wizyty'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Data utworzenia rekordu wizyty'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Data ostatniej modyfikacji rekordu'),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
