"""Dodanie nowych pól lub aktualizacja schematu

Revision ID: 2217e9041918
Revises: 04679a25a6a4
Create Date: 2025-04-07 22:46:01.664929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2217e9041918'
down_revision: Union[str, None] = '04679a25a6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('consultants', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('totp_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'totp_secret')
    op.drop_column('consultants', 'totp_secret')
    op.drop_column('clients', 'totp_secret')
    # ### end Alembic commands ###
